services:
  image-processing-service:
    environment:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    working_dir: /app/src/image_processing_service
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--reload",
        "--reload-dir",
        "/app/src",
      ]
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    develop:
      watch:
        # Sync source code changes
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tests
          target: /app/tests
        # Rebuild on dependency changes
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  verification-service:
    environment:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    working_dir: /app/src/verification_service
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8002",
        "--reload",
        "--reload-dir",
        "/app/src",
      ]
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    develop:
      watch:
        # Sync source code changes
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tests
          target: /app/tests
        # Rebuild on dependency changes
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  web-interface:
    environment:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    working_dir: /app/src/web_interface
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
        "--reload-dir",
        "/app/src",
      ]
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    develop:
      watch:
        # Sync source code changes
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tests
          target: /app/tests
        # Rebuild React app on changes
        - action: rebuild
          path: ./src/web_interface/src
        - action: rebuild
          path: ./src/web_interface/package.json
        # Rebuild on dependency changes
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
